package com.appodealx.openrtb

case class Bid(id: String,
               impid: String,
               price: Double,
               adid: Option[String] = None,
               nurl: Option[String] = None,
               burl: Option[String] = None,
               lurl: Option[String] = None,
               adm: Option[String] = None,
               adomain: Option[List[String]] = None,
               bundle: Option[String] = None,
               iurl: Option[Url] = None,
               cid: Option[String] = None,
               crid: Option[String] = None,
               tactic: Option[String] = None,
               cat: Option[List[String]] = None,
               attr: Option[List[CreativeAttribute]] = None,
               api: Option[ApiFramework] = None,
               protocol: Option[Protocol] = None,
               qagmediarating: Option[QagMediaRating] = None,
               language: Option[String] = None,
               dealid: Option[String] = None,
               h: Option[Int] = None,
               w: Option[Int] = None,
               wratio: Option[Int] = None,
               hratio: Option[Int] = None,
               exp: Option[Int] = None,
               ext: Option[Json] = None)
